{
 "title": "Crawling_Dashboard",
 "description": "Dashboard to view real time statistics on a crawling script",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Crawls",
    "label": "Crawls",
    "query": "SELECT crawl_id FROM crawl_info;"
   },
   {
    "name": "Clusters",
    "label": "Clusters",
    "query": "SELECT cluster_id FROM crawl_info; "
   },
   {
    "name": "Domains",
    "label": "Domains",
    "query": "SELECT DISTINCT domain_name FROM crawl_info;"
   }
  ]
 },
 "panels": [
  {
   "title": "Aggregate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Cost per Crawl",
     "type": "stat",
     "description": "Average cost for each crawl",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "dataset": "crawl_vis", "rawSql": "SELECT cost FROM crawl_info;" }
     ]
    },
    {
     "title": "GigaBytes Downloaded Per Proxy",
     "type": "barchart",
     "description": "total amount of gigabytes downloaded grouped by proxy",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT proxy, request_id FROM request_info;"
      },
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT request_id, bytes_downloaded FROM response_info;"
      }
     ]
    }
   ]
  },
  {
   "title": "Concurrent Requests vs Response Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    { "title": "$Domains", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 } },
    { "title": "$Domains", "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 } }
   ]
  },
  {
   "title": "Cluster ID: $Clusters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "Clusters",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "description": "Total CPU utilization over time for this cluster",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "dataset": "crawls",
       "rawSql": "SELECT node_info.node_id, node_info.cpu_usage, node_info.time \r\nFROM node_info \r\nJOIN crawl_node ON node_info.node_id = crawl_node.node_id \r\nJOIN crawl_info ON crawl_node.crawl_id = crawl_info.crawl_id \r\nWHERE crawl_info.cluster_id = $Clusters AND $__timeFilter(node_info.time);"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "description": "Total RAM utilization",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT node_info.node_id, node_info.memory_usage, node_info.time \r\nFROM node_info \r\nJOIN crawl_node ON node_info.node_id = crawl_node.node_id \r\nJOIN crawl_info ON crawl_node.crawl_id = crawl_info.crawl_id \r\nWHERE crawl_info.cluster_id = $Clusters AND $__timeFilter(node_info.time);"
      }
     ]
    },
    {
     "title": "Storage",
     "type": "timeseries",
     "description": "Total Disk Sapce utilization",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT node_info.node_id, node_info.diskspace_usage, node_info.time \r\nFROM node_info \r\nJOIN crawl_node ON node_info.node_id = crawl_node.node_id \r\nJOIN crawl_info ON crawl_node.crawl_id = crawl_info.crawl_id \r\nWHERE crawl_info.cluster_id = $Clusters AND $__timeFilter(node_info.time);"
      }
     ]
    },
    {
     "title": "Bandwidth",
     "type": "timeseries",
     "description": "Total Network utilization",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT node_info.node_id, node_info.bandwidth_usage, node_info.time \r\nFROM node_info \r\nJOIN crawl_node ON node_info.node_id = crawl_node.node_id \r\nJOIN crawl_info ON crawl_node.crawl_id = crawl_info.crawl_id \r\nWHERE crawl_info.cluster_id = $Clusters AND $__timeFilter(node_info.time);"
      }
     ]
    }
   ]
  },
  {
   "title": "Crawl ID: $Crawls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "Crawls",
   "collapsed": true,
   "panels": [
    {
     "title": "Cost",
     "type": "stat",
     "description": "cost for this crawl",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT cost FROM crawl_info WHERE crawl_id = $Crawls;"
      }
     ]
    },
    {
     "title": "Requests Per Second",
     "type": "stat",
     "description": "Requests per Second for this crawl",
     "gridPos": { "h": 3, "w": 5, "x": 4, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT requests_per_sec FROM crawl_info WHERE crawl_id = $Crawls;"
      }
     ]
    },
    {
     "title": "API Status Code",
     "type": "stat",
     "description": "API status code for this crawl",
     "gridPos": { "h": 3, "w": 5, "x": 9, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT api_status_code FROM crawl_info WHERE crawl_id = $Crawls; "
      }
     ]
    },
    {
     "title": "Concurrent Requests",
     "type": "stat",
     "description": "Amount of requests sent at one time for this crawl",
     "gridPos": { "h": 3, "w": 5, "x": 14, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT concurrent_requests FROM crawl_info WHERE crawl_id = $Crawls"
      }
     ]
    },
    { "title": "Time Remaining", "gridPos": { "h": 6, "w": 5, "x": 19, "y": 4 } },
    { "title": "Requests Remaining", "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 } },
    { "title": "Gigabytes Downloaded", "gridPos": { "h": 3, "w": 5, "x": 5, "y": 7 } },
    { "title": "Blocked Requests", "gridPos": { "h": 3, "w": 5, "x": 10, "y": 7 } },
    {
     "title": "Error Rate",
     "type": "stat",
     "description": "Count of all 4xx, 5xx, and isBlocked errors for this crawl",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT COUNT(is_blocked) FROM response_info WHERE crawl_id = $Crawls AND is_blocked = 1;"
      },
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT COUNT(website_status_code) FROM response_info WHERE crawl_id = $Crawls AND website_status_code > 399;"
      },
      { "expression": "$A + $B", "type": "math" }
     ]
    },
    { "title": "Website Status Code", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 } },
    { "title": "Download Speed Over Time", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 } }
   ]
  }
 ]
}