{
 "title": "Crawling_Dashboard",
 "description": "Dashboard to view real time statistics on a crawling script",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Crawls",
    "label": "Crawls",
    "query": "SELECT crawl_id FROM crawl_info;"
   },
   {
    "name": "Clusters",
    "label": "Clusters",
    "query": "SELECT cluster_id FROM crawl_info; "
   }
  ]
 },
 "panels": [
  {
   "title": "Aggregate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "GigaBytes Downloaded Per Proxy",
     "type": "barchart",
     "description": "total amount of gigabytes downloaded grouped by proxy",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT proxy, request_id FROM request_info;"
      },
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT request_id, bytes_downloaded FROM response_info;"
      }
     ]
    },
    {
     "title": "Concurrent Requests vs Response Time",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 }
    }
   ]
  },
  {
   "title": "Cluster ID: $Clusters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "Clusters",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "description": "Total CPU utilization over time for this cluster",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "targets": [
      {
       "dataset": "crawls",
       "rawSql": "SELECT cpu_usage, time FROM node_info WHERE node_id IN (SELECT node_id FROM crawl_node WHERE crawl_id IN (SELECT crawl_id FROM crawl_info WHERE cluster_id = $Clusters));"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "description": "Total RAM utilization",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
     "targets": [
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT memory_usage, time FROM node_info WHERE node_id IN (SELECT node_id FROM crawl_node WHERE crawl_id IN (SELECT crawl_id FROM crawl_info WHERE cluster_id = $Clusters));"
      }
     ]
    },
    {
     "title": "Storage",
     "type": "timeseries",
     "description": "Total Disk Sapce utilization",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
     "targets": [
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT diskspace_usage, time FROM node_info WHERE node_id IN (SELECT node_id FROM crawl_node WHERE crawl_id IN (SELECT crawl_id FROM crawl_info WHERE cluster_id = $Clusters));"
      }
     ]
    },
    {
     "title": "Bandwidth",
     "type": "timeseries",
     "description": "Total Network utilization",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
     "targets": [
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT cpu_usage, time FROM node_info WHERE node_id IN (SELECT node_id FROM crawl_node WHERE crawl_id IN (SELECT crawl_id FROM crawl_info WHERE cluster_id = $Clusters));"
      }
     ]
    }
   ]
  },
  {
   "title": "Crawl ID: $Crawls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "Crawls",
   "collapsed": true,
   "panels": [
    { "title": "Requests Remainig", "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 } },
    { "title": "Gigabytes Downloaded", "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 } },
    { "title": "Estimated Time to Completion", "gridPos": { "h": 4, "w": 4, "x": 10, "y": 4 } },
    { "title": "Blocked Requests", "gridPos": { "h": 4, "w": 5, "x": 14, "y": 4 } },
    {
     "title": "Concurrent Requests",
     "type": "stat",
     "description": "Amount of requests sent at one time for this crawl",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT concurrent_requests FROM crawl_info WHERE crawl_id = $Crawls"
      }
     ]
    },
    { "title": "Website Status Code", "gridPos": { "h": 14, "w": 6, "x": 0, "y": 8 } },
    { "title": "Download Speed Over Time", "gridPos": { "h": 7, "w": 18, "x": 6, "y": 8 } },
    {
     "title": "Number of Responses over Time",
     "type": "timeseries",
     "description": "count of responses received at each moment in time",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 15 },
     "targets": [
      {
       "dataset": "crawl_vis",
       "rawSql": "SELECT response_id, time FROM response_info WHERE crawl_id = $Crawls;"
      }
     ]
    }
   ]
  }
 ]
}